run:
  timeout: 2m
  go: "1.23" # Set Go version to 1.23

linters:
  disable-all: true
  enable:
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - bodyclose
    - misspell
    - gofumpt
    - goconst
    - unconvert
