// Code generated by go-hubspot/tools/model_generator/model_gen.go; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package hubspot

type Company struct {
	AboutUs                                 *HsStr  `json:"about_us,omitempty"`
	Address                                 *HsStr  `json:"address,omitempty"`
	Address2                                *HsStr  `json:"address2,omitempty"`
	Annualrevenue                           *HsInt  `json:"annualrevenue,omitempty"`
	City                                    *HsStr  `json:"city,omitempty"`
	Closedate                               *HsTime `json:"closedate,omitempty"`
	Country                                 *HsStr  `json:"country,omitempty"`
	Createdate                              *HsTime `json:"createdate,omitempty"`
	DaysToClose                             *HsInt  `json:"days_to_close,omitempty"`
	Description                             *HsStr  `json:"description,omitempty"`
	Domain                                  *HsStr  `json:"domain,omitempty"`
	EngagementsLastMeetingBooked            *HsTime `json:"engagements_last_meeting_booked,omitempty"`
	EngagementsLastMeetingBookedCampaign    *HsStr  `json:"engagements_last_meeting_booked_campaign,omitempty"`
	EngagementsLastMeetingBookedMedium      *HsStr  `json:"engagements_last_meeting_booked_medium,omitempty"`
	EngagementsLastMeetingBookedSource      *HsStr  `json:"engagements_last_meeting_booked_source,omitempty"`
	FacebookCompanyPage                     *HsStr  `json:"facebook_company_page,omitempty"`
	Facebookfans                            *HsInt  `json:"facebookfans,omitempty"`
	FirstContactCreatedate                  *HsTime `json:"first_contact_createdate,omitempty"`
	FirstConversionDate                     *HsTime `json:"first_conversion_date,omitempty"`
	FirstConversionEventName                *HsStr  `json:"first_conversion_event_name,omitempty"`
	FirstDealCreatedDate                    *HsTime `json:"first_deal_created_date,omitempty"`
	FoundedYear                             *HsStr  `json:"founded_year,omitempty"`
	GoogleplusPage                          *HsStr  `json:"googleplus_page,omitempty"`
	HsAnalyticsFirstTimestamp               *HsTime `json:"hs_analytics_first_timestamp,omitempty"`
	HsAnalyticsFirstTouchConvertingCampaign *HsStr  `json:"hs_analytics_first_touch_converting_campaign,omitempty"`
	HsAnalyticsFirstVisitTimestamp          *HsTime `json:"hs_analytics_first_visit_timestamp,omitempty"`
	HsAnalyticsLastTimestamp                *HsTime `json:"hs_analytics_last_timestamp,omitempty"`
	HsAnalyticsLastTouchConvertingCampaign  *HsStr  `json:"hs_analytics_last_touch_converting_campaign,omitempty"`
	HsAnalyticsLastVisitTimestamp           *HsTime `json:"hs_analytics_last_visit_timestamp,omitempty"`
	HsAnalyticsLatestSource                 *HsStr  `json:"hs_analytics_latest_source,omitempty"`
	HsAnalyticsLatestSourceData1            *HsStr  `json:"hs_analytics_latest_source_data_1,omitempty"`
	HsAnalyticsLatestSourceData2            *HsStr  `json:"hs_analytics_latest_source_data_2,omitempty"`
	HsAnalyticsLatestSourceTimestamp        *HsTime `json:"hs_analytics_latest_source_timestamp,omitempty"`
	HsAnalyticsNumPageViews                 *HsInt  `json:"hs_analytics_num_page_views,omitempty"`
	HsAnalyticsNumVisits                    *HsInt  `json:"hs_analytics_num_visits,omitempty"`
	HsAnalyticsSource                       *HsStr  `json:"hs_analytics_source,omitempty"`
	HsAnalyticsSourceData1                  *HsStr  `json:"hs_analytics_source_data_1,omitempty"`
	HsAnalyticsSourceData2                  *HsStr  `json:"hs_analytics_source_data_2,omitempty"`
	HsCreatedByUserId                       *HsInt  `json:"hs_created_by_user_id,omitempty"`
	HsCreatedate                            *HsTime `json:"hs_createdate,omitempty"`
	HsIdealCustomerProfile                  *HsStr  `json:"hs_ideal_customer_profile,omitempty"`
	HsIsTargetAccount                       *HsBool `json:"hs_is_target_account,omitempty"`
	HsLastBookedMeetingDate                 *HsTime `json:"hs_last_booked_meeting_date,omitempty"`
	HsLastLoggedCallDate                    *HsTime `json:"hs_last_logged_call_date,omitempty"`
	HsLastOpenTaskDate                      *HsTime `json:"hs_last_open_task_date,omitempty"`
	HsLastSalesActivityTimestamp            *HsTime `json:"hs_last_sales_activity_timestamp,omitempty"`
	HsLastmodifieddate                      *HsTime `json:"hs_lastmodifieddate,omitempty"`
	HsLeadStatus                            *HsStr  `json:"hs_lead_status,omitempty"`
	HsMergedObjectIds                       *HsStr  `json:"hs_merged_object_ids,omitempty"`
	HsNumBlockers                           *HsInt  `json:"hs_num_blockers,omitempty"`
	HsNumChildCompanies                     *HsInt  `json:"hs_num_child_companies,omitempty"`
	HsNumContactsWithBuyingRoles            *HsInt  `json:"hs_num_contacts_with_buying_roles,omitempty"`
	HsNumDecisionMakers                     *HsInt  `json:"hs_num_decision_makers,omitempty"`
	HsNumOpenDeals                          *HsInt  `json:"hs_num_open_deals,omitempty"`
	HsObjectId                              *HsInt  `json:"hs_object_id,omitempty"`
	HsParentCompanyId                       *HsInt  `json:"hs_parent_company_id,omitempty"`
	HsTotalDealValue                        *HsInt  `json:"hs_total_deal_value,omitempty"`
	HubspotOwnerAssigneddate                *HsTime `json:"hubspot_owner_assigneddate,omitempty"`
	HubspotOwnerId                          *HsStr  `json:"hubspot_owner_id,omitempty"`
	HubspotTeamId                           *HsStr  `json:"hubspot_team_id,omitempty"`
	Industry                                *HsStr  `json:"industry,omitempty"`
	IsPublic                                *HsBool `json:"is_public,omitempty"`
	Lifecyclestage                          *HsStr  `json:"lifecyclestage,omitempty"`
	LinkedinCompanyPage                     *HsStr  `json:"linkedin_company_page,omitempty"`
	Linkedinbio                             *HsStr  `json:"linkedinbio,omitempty"`
	Name                                    *HsStr  `json:"name,omitempty"`
	NotesLastContacted                      *HsTime `json:"notes_last_contacted,omitempty"`
	NotesLastUpdated                        *HsTime `json:"notes_last_updated,omitempty"`
	NotesNextActivityDate                   *HsTime `json:"notes_next_activity_date,omitempty"`
	NumAssociatedContacts                   *HsInt  `json:"num_associated_contacts,omitempty"`
	NumAssociatedDeals                      *HsInt  `json:"num_associated_deals,omitempty"`
	NumContactedNotes                       *HsInt  `json:"num_contacted_notes,omitempty"`
	NumConversionEvents                     *HsInt  `json:"num_conversion_events,omitempty"`
	Numberofemployees                       *HsInt  `json:"numberofemployees,omitempty"`
	Phone                                   *HsStr  `json:"phone,omitempty"`
	RecentConversionDate                    *HsTime `json:"recent_conversion_date,omitempty"`
	RecentConversionEventName               *HsStr  `json:"recent_conversion_event_name,omitempty"`
	RecentDealAmount                        *HsStr  `json:"recent_deal_amount,omitempty"`
	RecentDealCloseDate                     *HsTime `json:"recent_deal_close_date,omitempty"`
	State                                   *HsStr  `json:"state,omitempty"`
	Timezone                                *HsStr  `json:"timezone,omitempty"`
	TotalMoneyRaised                        *HsStr  `json:"total_money_raised,omitempty"`
	TotalRevenue                            *HsInt  `json:"total_revenue,omitempty"`
	Twitterbio                              *HsStr  `json:"twitterbio,omitempty"`
	Twitterfollowers                        *HsInt  `json:"twitterfollowers,omitempty"`
	Twitterhandle                           *HsStr  `json:"twitterhandle,omitempty"`
	Type                                    *HsStr  `json:"type,omitempty"`
	WebTechnologies                         *HsStr  `json:"web_technologies,omitempty"`
	Website                                 *HsStr  `json:"website,omitempty"`
	Zip                                     *HsStr  `json:"zip,omitempty"`
}

var defaultCompanyFields = []string{
	"about_us",
	"address",
	"address2",
	"annualrevenue",
	"city",
	"closedate",
	"country",
	"createdate",
	"days_to_close",
	"description",
	"domain",
	"engagements_last_meeting_booked",
	"engagements_last_meeting_booked_campaign",
	"engagements_last_meeting_booked_medium",
	"engagements_last_meeting_booked_source",
	"facebook_company_page",
	"facebookfans",
	"first_contact_createdate",
	"first_conversion_date",
	"first_conversion_event_name",
	"first_deal_created_date",
	"founded_year",
	"googleplus_page",
	"hs_analytics_first_timestamp",
	"hs_analytics_first_touch_converting_campaign",
	"hs_analytics_first_visit_timestamp",
	"hs_analytics_last_timestamp",
	"hs_analytics_last_touch_converting_campaign",
	"hs_analytics_last_visit_timestamp",
	"hs_analytics_latest_source",
	"hs_analytics_latest_source_data_1",
	"hs_analytics_latest_source_data_2",
	"hs_analytics_latest_source_timestamp",
	"hs_analytics_num_page_views",
	"hs_analytics_num_visits",
	"hs_analytics_source",
	"hs_analytics_source_data_1",
	"hs_analytics_source_data_2",
	"hs_created_by_user_id",
	"hs_createdate",
	"hs_ideal_customer_profile",
	"hs_is_target_account",
	"hs_last_booked_meeting_date",
	"hs_last_logged_call_date",
	"hs_last_open_task_date",
	"hs_last_sales_activity_timestamp",
	"hs_lastmodifieddate",
	"hs_lead_status",
	"hs_merged_object_ids",
	"hs_num_blockers",
	"hs_num_child_companies",
	"hs_num_contacts_with_buying_roles",
	"hs_num_decision_makers",
	"hs_num_open_deals",
	"hs_object_id",
	"hs_parent_company_id",
	"hs_total_deal_value",
	"hubspot_owner_assigneddate",
	"hubspot_owner_id",
	"hubspot_team_id",
	"industry",
	"is_public",
	"lifecyclestage",
	"linkedin_company_page",
	"linkedinbio",
	"name",
	"notes_last_contacted",
	"notes_last_updated",
	"notes_next_activity_date",
	"num_associated_contacts",
	"num_associated_deals",
	"num_contacted_notes",
	"num_conversion_events",
	"numberofemployees",
	"phone",
	"recent_conversion_date",
	"recent_conversion_event_name",
	"recent_deal_amount",
	"recent_deal_close_date",
	"state",
	"timezone",
	"total_money_raised",
	"total_revenue",
	"twitterbio",
	"twitterfollowers",
	"twitterhandle",
	"type",
	"web_technologies",
	"website",
	"zip",
}
